### ISSUE TITLE
ArgumentError: row indices I[k] must satisfy 1 <= I[k] <= m

### ISSUE THREAD

**Issue by tarunkumariitm** [tdunning/LLR#1]
I am trying the following code:

```
A = [0 1 1; 1 1 0]
using LLR
ind = LLR.indicators(A)

```
It gives me the following error

> ArgumentError: row indices I[k] must satisfy 1 <= I[k] <= m
> 
> Stacktrace:
>   [1] sparse!(I::Vector{Int64}, J::Vector{Int64}, V::Vector{Float64}, m::Int64, n::Int64, combine::typeof(+), klasttouch::Vector{Int64}, csrrowptr::Vector{Int64}, csrcolval::Vector{Int64}, csrnzval::Vector{Float64}, csccolptr::Vector{Int64}, cscrowval::Vector{Int64}, cscnzval::Vector{Float64})
>     @ SparseArrays /opt/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/sparsematrix.jl:870
>   [2] sparse(I::Vector{Int64}, J::Vector{Int64}, V::Vector{Float64}, m::Int64, n::Int64, combine::Function)
>     @ SparseArrays /opt/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/sparsematrix.jl:798
>   [3] sparse
>     @ /opt/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/sparsematrix.jl:987 [inlined]
>   [4] indicators(A::SparseArrays.SparseMatrixCSC{Int64, Int64}; itemcut::Int64, rowcut::Int64)
>     @ LLR ~/.julia/packages/LLR/Fi6NN/src/LLR.jl:133
>   [5] indicators
>     @ ~/.julia/packages/LLR/Fi6NN/src/LLR.jl:67 [inlined]
>   [6] #indicators#1
>     @ ~/.julia/packages/LLR/Fi6NN/src/LLR.jl:63 [inlined]
>   [7] indicators(A::Matrix{Int64})
>     @ LLR ~/.julia/packages/LLR/Fi6NN/src/LLR.jl:63
>   [8] top-level scope
>     @ In[4]:2
>   [9] eval
>     @ ./boot.jl:373 [inlined]
>  [10] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
>     @ Base ./loading.jl:1196
> 

The code works when I use the following code:
```
A = [0 1; 1 1; 1 0]
using LLR
ind = LLR.indicators(A)

```
Does the method LLR.indicators() expect a matrix with num_rows>num_columns ?

**Comment by tdunning** [comment]
Yeah... there is a sparse constructor in there that needs to pass in desired size.

As it is, if there isn't an entry in the last row or column, the size will be deficient.

Let me think about how to write a test case. If you think of one before I do, pipe up.

**Comment by tdunning** [comment]
Hmmm... my comment does not seem related to your issue (and I fixed the issue I was talking about already)

Something else is happening, possibly due to an unusual shape of input (perhaps wide data?)

Still looking.

**Comment by tdunning** [comment]
Got it.
